### ISSUE TITLE
切换到中文的时候，点击保存用户设置的”*“星号不会消失

### ISSUE THREAD

**Issue by 26500-R** [Mister-Kin/ToggleLanguage#1]
![GIF 2022-9-14 18-58-43](https://user-images.githubusercontent.com/99272533/190136835-ffa07501-253a-42ce-a799-61a6c924e132.gif)
blender3.2.2&win11

**Comment by Mister-Kin** [comment]
刚测试了v3.3.0&win10，切换非English都会复现这个问题。

一直都是使用`Auto-Save Preferences`功能，没注意到手动保存有这个问题存在。

我回头看看是不是operator执行的刷新问题。

**Comment by Mister-Kin** [comment]
Just fixed it.
