### ISSUE TITLE
Blender 4.0 閜使用似乎有問題

### ISSUE THREAD

**Issue by bisechen** [Mister-Kin/ToggleLanguage#2]
感謝作者提供這個好用的外掛。

今天在4.0版環境測試使用，有底下這些錯誤訊息。

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ToggleLanguage\operators.py", line 31, in execute
    userpref.view.language = addonpref.first_lang
TypeError: bpy_struct: item.attr = val: enum "zh_CN" not found in ('DEFAULT', 'ca_AD', 'en_US', 'es', 'fr_FR', 'ja_JP', 'sk_SK', 'cs_CZ', 'de_DE', 'it_IT', 'ka', 'ko_KR', 'pt_BR', 'pt_PT', 'ru_RU', 'uk_UA', 'vi_VN', 'zh_HANS', 'zh_HANT', 'ab', 'ar_EG', 'bg_BG', 'el_GR', 'eo', 'eu_EU', 'fa_IR', 'fi_FI', 'ha', 'he_IL', 'hi_IN', 'hr_HR', 'hu_HU', 'id_ID', 'ky_KG', 'ne_NP', 'nl_NL', 'pl_PL', 'sr_RS', 'sr_RS@latin', 'sv_SE', 'sw', 'ta', 'th_TH', 'tr_TR')

**Comment by Mister-Kin** [comment]
> 感謝作者提供這個好用的外掛。
> 
> 今天在4.0版環境測試使用，有底下這些錯誤訊息。
> 
> Python: Traceback (most recent call last): File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ToggleLanguage\operators.py", line 31, in execute userpref.view.language = addonpref.first_lang TypeError: bpy_struct: item.attr = val: enum "zh_CN" not found in ('DEFAULT', 'ca_AD', 'en_US', 'es', 'fr_FR', 'ja_JP', 'sk_SK', 'cs_CZ', 'de_DE', 'it_IT', 'ka', 'ko_KR', 'pt_BR', 'pt_PT', 'ru_RU', 'uk_UA', 'vi_VN', 'zh_HANS', 'zh_HANT', 'ab', 'ar_EG', 'bg_BG', 'el_GR', 'eo', 'eu_EU', 'fa_IR', 'fi_FI', 'ha', 'he_IL', 'hi_IN', 'hr_HR', 'hu_HU', 'id_ID', 'ky_KG', 'ne_NP', 'nl_NL', 'pl_PL', 'sr_RS', 'sr_RS@latin', 'sv_SE', 'sw', 'ta', 'th_TH', 'tr_TR')

v4.0改动了语言编码：`zh_CN`->`zh_HANS`，我抽空迭代更新一个版本来支持v4.0的改动。

**Comment by Mister-Kin** [comment]
Just fixed it.
